// noinspection JSUnusedGlobalSymbols

export enum Easing {
  LINEAR = 'linear.none',
  EASE_IN = 'ease.in',
  EASE_OUT = 'ease.out',
  EASE_INOUT = 'ease.inout',
  SIN_IN = 'sin.in',
  SIN_OUT = 'sin.out',
  SIN_INOUT = 'sin.inout',
  QUAD_IN = 'quad.in',
  QUAD_OUT = 'quad.out',
  QUAD_INOUT = 'quad.inout',
  CUBIC_IN = 'cubic.in',
  CUBIC_OUT = 'cubic.out',
  CUBIC_INOUT = 'cubic.inout',
  QUART_IN = 'quart.in',
  QUART_OUT = 'quart.out',
  QUART_INOUT = 'quart.inout',
  QUINT_IN = 'quint.in',
  QUINT_OUT = 'quint.out',
  QUINT_INOUT = 'quint.inout',
  EXPO_IN = 'expo.in',
  EXPO_OUT = 'expo.out',
  EXPO_INOUT = 'expo.inout',
  CIRC_IN = 'circ.in',
  CIRC_OUT = 'circ.out',
  CIRC_INOUT = 'circ.inout',
  BACK_IN = 'back.in',
  BACK_OUT = 'back.out',
  BACK_INOUT = 'back.inout',
  ELASTIC_IN = 'elastic.in',
  ELASTIC_OUT = 'elastic.out',
  ELASTIC_INOUT = 'elastic.inout',
  BOUNCE_IN = 'bounce.in',
  BOUNCE_OUT = 'bounce.out',
  BOUNCE_INOUT = 'bounce.inout'
}
